### ISSUE TITLE
Spinner arrow is always white API < 21

### ISSUE THREAD

**Issue by zCode93** [michael-rapp/AndroidMaterialValidation#2]
Tint color is not applied to Spinner arrow when API < 21. Arrow appears **white**

Tried _colorControlNormal_ / _colorControlActivated_ but didn't work.

**Comment by michael-rapp** [comment]
Thank you for the bug report. I was able to reproduce the issue and already found a solution. It has to be fixed on the side of the library. I will prepare a bugfix release.

**Comment by michael-rapp** [comment]
Fixed in version 2.1.2.
